import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { FileText, Download } from "lucide-react";

const proposals = [
  { id: 1, company: "Acme Corp", date: "Oct 24, 2026", amount: "$120,000", status: "Sent", type: "Enterprise License" },
  { id: 2, company: "Globex Inc", date: "Oct 22, 2026", amount: "$45,000", status: "Draft", type: "Implementation" },
  { id: 3, company: "Initech", date: "Oct 20, 2026", amount: "$80,000", status: "Accepted", type: "Expansion" },
];

export default function Proposals() {
  return (
    <div className="flex flex-col gap-6 pb-12">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Proposals</h1>
        <p className="text-muted-foreground mt-2">
          Review proposals generated by the Proposal Agent and managed in Cloud Storage.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Recent Proposals</CardTitle>
          <CardDescription>
            Proposals with executive summaries, scope, pricing, and timelines.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Company</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Amount</TableHead>
                <TableHead>Date Generated</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {proposals.map((proposal) => (
                <TableRow key={proposal.id}>
                  <TableCell className="font-medium">{proposal.company}</TableCell>
                  <TableCell>{proposal.type}</TableCell>
                  <TableCell className="font-bold">{proposal.amount}</TableCell>
                  <TableCell>{proposal.date}</TableCell>
                  <TableCell>
                    <Badge variant="outline" className={
                      proposal.status === 'Accepted' ? 'text-green-500 border-green-500/20 bg-green-500/10' :
                      proposal.status === 'Sent' ? 'text-blue-500 border-blue-500/20 bg-blue-500/10' :
                      'text-gray-500 border-gray-500/20 bg-gray-500/10'
                    }>
                      {proposal.status}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-right">
                    <button className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors hover:bg-muted hover:text-foreground h-9 w-9">
                      <Download className="h-4 w-4" />
                      <span className="sr-only">Download</span>
                    </button>
                    <button className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors hover:bg-muted hover:text-foreground h-9 w-9 ml-2">
                      <FileText className="h-4 w-4" />
                      <span className="sr-only">View PDF</span>
                    </button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
